spring:
  application:
    name: order  # the same with com.yiqiniu.easytrans.demos.order.Constant.APPID
  datasource: # order service datasource config
    url: jdbc:mysql://127.0.0.1:3306/tcc_inventory?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server: 
  port: 8083

# RIBBON用，也可以直接开启Eureka
order-service:
  ribbon:
    listOfServers: localhost:8080
pay-service:
  ribbon:
    listOfServers: localhost:8081
inventory-service:
  ribbon:
    listOfServers: localhost:8082

easytrans:
  master:
    zk:
      zooKeeperUrl: localhost:2181
  rpc:
    dubbo:
      enabled: true
      dubbo-zk-url: zookeeper://${easytrans.master.zk.zooKeeperUrl}
  stringcodec:
    zk:
      zooKeeperUrl: ${easytrans.master.zk.zooKeeperUrl}
  idgen:
    trxId:
      zkSnow:
        zooKeeperUrl: ${easytrans.master.zk.zooKeeperUrl}
  log:
    database:
      logCleanEnabled: true
      logReservedDays: 14
      logCleanTime: 01:22:00
      druid:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ncdb57?characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456



    
      